modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
[[mods]] #mandatory
modId="crafttweaks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Jake's Crafting Tweaks" #mandatory
logoFile="examplemod.png" #optional
authors="JakeTrevor" #optional
description='''
some crafting recipe tweaks for botch modded s3
'''
[[dependencies.crafttweaks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.crafttweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.crafttweaks]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.i,)"
    ordering="NONE"
    side="BOTH"